### ISSUE TITLE
Error on python program

### ISSUE THREAD

**Issue by jamesyao54** [fleet-ai/context#37]
Traceback (most recent call last):
  File "/Users/user/Code/server/app/services/intelligence/components/retriever.py", line 59, in <module>
    from context import download_embeddings
  File "/Users/user/Code/server/.venv/lib/python3.10/site-packages/context.py", line 6, in <module>
    from utils.ai import retrieve
ModuleNotFoundError: No module named 'utils.ai'

**Comment by maxvonhippel** [comment]
I've reproduced the same error on Mac OS 14.5 (23F79).

```
from context import query

results = query("How do I set up Langchain?")
for result in results:
    print(f"{result['metadata']['text']}\n{result['metadata']['text']}")
```

> Traceback (most recent call last):
  File [ removed file path for privacy ...], line 1, in <module>
    from context import query
  File "/Users/maxvonhippel/Library/Python/3.9/lib/python/site-packages/context.py", line 6, in <module>
    from utils.ai import retrieve
ModuleNotFoundError: No module named 'utils.ai'; 'utils' is not a package
