### ISSUE TITLE
json formatting issue?

### ISSUE THREAD

**Issue by ssergorp** [fleet-ai/context#38]
I've tried installing and running context on 2 linux and 1 windows machine and get this same json related error each time. It will ask me for an api key and then I get this if I try and use the cli:

``
Traceback (most recent call last):
  File "C:\Users\19729\anaconda3\envs\fleet\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19729\anaconda3\envs\fleet\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19729\anaconda3\envs\fleet\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19729\anaconda3\envs\fleet\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\19729\anaconda3\envs\fleet\Scripts\context.exe\__main__.py", line 7, in <module>
  File "C:\Users\19729\anaconda3\envs\fleet\Lib\site-packages\cli.py", line 204, in main
    rag_context = retrieve_context(
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\19729\anaconda3\envs\fleet\Lib\site-packages\utils\ai.py", line 52, in retrieve_context
    responses = retrieve(query, k=k, filters=filters)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19729\anaconda3\envs\fleet\Lib\site-packages\utils\ai.py", line 40, in retrieve
    return requests.post(url, json=params, timeout=120).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19729\anaconda3\envs\fleet\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``

**Comment by kanvgupta** [comment]
Similar issue. Tried it with Python (3.9, 3.10 and 3.11).

`Welcome to Fleet Context!
Generate and run code using the most up-to-date libraries.                      


> hi
Traceback (most recent call last):
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/bin/context", line 8, in <module>
    sys.exit(main())
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/lib/python3.9/site-packages/cli.py", line 204, in main
    rag_context = retrieve_context(
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/lib/python3.9/site-packages/utils/ai.py", line 52, in retrieve_context
    responses = retrieve(query, k=k, filters=filters)
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/lib/python3.9/site-packages/utils/ai.py", line 40, in retrieve
    return requests.post(url, json=params, timeout=120).json()
  File "/Users/kanvgupta/.pyenv/versions/3.9.18/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by SpecterHi** [comment]
Similar issue as above
