### ISSUE TITLE
App says missing key, not true

### ISSUE THREAD

**Issue by grexzen** [fleet-ai/context#9]
Welcome to Fleet Context!
Generate and run code using the most up-to-date libraries.

> 0

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\utils\ai.py", line 154, in get_openai_chat_response
    response = openai.chat.completions.create(
AttributeError: module 'openai' has no attribute 'chat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\context.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\cli.py", line 147, in main
    for response in get_openai_chat_response(prompts, model=model):
  File "C:\Program Files\Python310\lib\site-packages\utils\ai.py", line 163, in get_openai_chat_response
    except openai.AuthenticationError as error:
AttributeError: module 'openai' has no attribute 'AuthenticationError'

------------------------------

Thanks for sharing embeddings! I ran into some issues w your app. Fixed them to start, but now it says no key, but the other apps using the key work.

**Comment by adrwz** [comment]
Hey @grexzen! Seems like you're on an older version of openai. Try running `pip install --upgrade openai` and this should be resolved.
